springs:
- joint_name: joint0_0
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint0_1
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint0_2
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint0_3
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint0_4
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint1_0
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint1_1
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint1_2
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint1_3
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint1_4
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint2_0
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint2_1
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint2_2
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint2_3
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint2_4
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint3_0
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint3_1
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint3_2
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint3_3
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint3_4
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint4_0
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint4_1
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint4_2
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint4_3
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint4_4
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint5_0
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint5_1
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint5_2
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint5_3
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint5_4
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint6_0
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint6_1
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint6_2
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint6_3
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint6_4
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint7_0
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint7_1
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint7_2
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint7_3
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint7_4
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint8_0
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint8_1
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint8_2
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint8_3
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint8_4
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint9_0
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint9_1
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint9_2
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint9_3
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
- joint_name: joint9_4
  K: 2000
  D: 2000
  upper_limit: 0.1
  lower_limit: -0.1
  velocity_limit: 20.0
